---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
images:
  - name: bretfisher/wordsmith-api
    newName: ghcr.io/hardlydevops/wordsmith-api
    newTag: stable-20230714-8c5f603
  - name: bretfisher/wordsmith-web
    newName: ghcr.io/hardlydevops/wordsmith-web
    newTag: stable-20230714-fc211cb
configMapGenerator:
  - name: db-schema
    files:
      - words.sql
